%YAML:1.0
---
model_type: KANNALA_BRANDT
camera_name: new camere 1
image_width: 640
image_height: 480
projection_parameters:
   k2: 0.
   k3: 0.
   k4: 0.
   k5: 0.
   mu: 0.
   mv: 0.
   u0: 0.
   v0: 0.
