%YAML:1.0
---
model_type: PINHOLE
camera_name: test
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.
   k2: 0.
   p1: 0.
   p2: 0.
projection_parameters:
   fx: 988.
   fy: 996.
   cx: 630.
   cy: 335.
