%YAML:1.0
---
model_type: PINHOLE
camera_name: new camere 0
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.
   k2: 0.
   p1: 0.
   p2: 0.
projection_parameters:
   fx: 0.
   fy: 0.
   cx: 0.
   cy: 0.
